1. 回调函数：第一个参数为 `Error` 或 `null` 错误对象（如果有错误发生的话），其余参数为正常的返回数据

```JavaScript
fs.readFile("/path/to/file", (err, data) => {
  if (err) {
    console.error(err);
    return;
  }
  console.log(data);
});
```

2. Promise

```JavaScript
fs.promises
  .readFile("/path/to/file")
  .then((data) => console.log(data))
  .catch((err) => console.error(err));
```

3. `async/await`

```JavaScript
const readFileAsync = async () => {
  try {
    const data = await fs.promises.readFile("/path/to/file");
    console.log(data);
  } catch (err) {
    console.error(err);
  }
};
```

4. `EventEmitter`

```JavaScript
const emitter = new EventEmitter();

emitter.on('error', err => console.error(err));
emitter.emit('error', new Error('simulate an error'));
```

5. 全局错误处理：使用 `process` 对象的 `uncaughtException` 事件监听器处理未捕获的异常，这是最后的防线，避免程序依赖此机制来处理错误

```JavaScript
process.on('uncaughtException', (err) => console.error('未捕获的异常:', err));
```